CREATE DATABASE gasolinera;

USE gasolinera;

CREATE TABLE `llista` (
  `index` bigint(20) DEFAULT NULL,
  `marca` text DEFAULT NULL,
  `direccio` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `llista`
--

INSERT INTO `llista` (`index`, `marca`, `direccio`) VALUES
(0, 'CEPSA', 'AVENIDA JOAN MIRO, 22'),
(1, 'GALP', 'CALLE MANUEL AZAÑA, 5'),
(2, 'REPSOL', 'CAMINO VILETA (LA), S/N'),
(3, 'SHELL', 'CALLE CAMI DE JESUS, 10'),
(4, 'REPSOL', 'CAMINO REIS, S/N'),
(5, 'AUTONETOIL', 'CALLE POIMA, 12'),
(6, 'BP BALMES', 'CALLE JAUME BALMES, 44'),
(7, 'BP AMANECER', 'CALLE ALFONS EL MAGNANIM, 90'),
(8, 'BP LLUCMAJOR', 'CALLE LLUCMAJOR, 109'),
(9, 'REPSOL', 'CALLE SANT IGNASI, 68'),
(10, 'REPSOL', 'CL CAMINO CA,N PASTILLA, 37 (CAMNIO CAN PASTILLA 37)'),
(11, 'REPSOL', 'CALLE CAPITAN SALOM, 31'),
(12, 'PETRONOR', 'CALLE GREMI DE SUCRERS I CANDELERS, 24'),
(13, 'SHELL', 'CALLE HORT DE SES ÀNIMES, 23'),
(14, 'REPSOL', 'CARRETERA C-711 PALMA-SOLLER KM. 7'),
(15, 'REPSOL', 'AVENIDA GABRIEL ALOMAR Y VILLALONGA, S/N'),
(16, 'CEPSA', 'CALLE CAMINO DE LOS REYES, 201'),
(17, 'BP ES FORTI', 'CALLE PASCUAL RIBOT, S/N'),
(18, 'REPSOL', 'CALLE CAMI VELL DE NUBYOLA, S/N'),
(19, 'REPSOL', 'CALLE GREMI SUCRERS Y CANDELERS, 5'),
(20, 'REPSOL', 'CALLE MANACOR, 309'),
(21, 'REPSOL', 'CALLE EUSEBIO ESTADA, 64'),
(22, 'PETROEST', 'CALLE GABRIEL ALZAMORA, 25'),
(23, 'PETROEST', 'CALLE GREMI CIRUGIANS I BARBERS, 11'),
(24, 'SET&GO', 'CALLE GREMI SELLETERS I BASTERS, 12'),
(25, 'REPSOL', 'CALLE ARAGON, 217'),
(26, 'CEPSA', 'CALLE BINIAMAR, 16'),
(27, 'REPSOL', 'CALLE ARAGON, 180'),
(28, 'AUTONETOIL', 'CARRER DE SON PENDOLA, 1'),
(29, 'REPSOL', 'CALLE LLUCMAJOR, 148'),
(30, 'CARREFOUR', 'AVENIDA CARDENAL ROSELL,, S/N'),
(31, 'CEPSA', 'CARRETERA VIEJA DE BUÑOLA KM. 15'),
(32, 'BP', 'AVENIDA AMERICA, ARENAL, 18'),
(33, 'BP', 'CALLE ANDREA DORIA, ESQUINA SON ARMADANS, S/N'),
(34, 'BP', 'AVENIDA JOAN MIRO, 238'),
(35, 'REPSOL', 'CAMI CAMI DE SON RAPINYA ESQ.CAMI DEL REIS, S/N'),
(36, 'BP', 'AVENIDA JOAN MIRO, S/N'),
(37, 'BP', 'CALLE TRAMUNTANA, S/N'),
(38, 'BP', 'CALLE MUSICO ISAAC ALBENIZ, S/N'),
(39, 'SHELL', 'CALLE GUADIANA, 45'),
(40, 'GALP', 'GRAN VÍA ASIMA, 23'),
(41, 'REPSOL', 'CALLE CAMI SALARD, S/N'),
(42, 'CEPSA', 'CAMINO DE LAS MARAVILLA, S/N'),
(43, 'REPSOL', 'CAMINO SON FANGOS, 151'),
(44, 'REPSOL', 'CALLE CALA BLANCA,, 9'),
(45, 'BP PLAYA DE PALMA', 'CALLE MANUELA DE LOS HERREROS, 15'),
(46, 'REPSOL', 'CARRETERA C-715 KM. 2,7'),
(47, 'REPSOL', 'PLAZA PROGRESO, S/N'),
(48, 'REPSOL', 'AE VIAL SALIDA AEROPUERTO, S.N.'),
(49, 'REPSOL', 'CALLE CORONEL BEORLEGUI, 49'),
(50, 'SHELL', 'CTA. MANACOR C-715 km 6.7'),
(51, 'CEPSA', 'CARRETERA LLUCMAJOR, KM10 KM. 10'),
(52, 'REPSOL', 'CALLE MANACOR, 336'),
(53, 'BP', 'CARRETERA 10, CAMINO DE CAN CAPO, SŽARANJASSA KM. 717'),
(54, 'REPSOL BUTANO', 'CAMI LA MILANA, 49');


--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `llista`
--
ALTER TABLE `llista`
  ADD PRIMARY KEY (`index`);

